export const paths = {
  STAC_ELEMENT_64_CATALOGUE: 'EODH_ELEMENT_84_CATALOGUE_API_URL',
  STAC_CEDA_CATALOGUE: 'EODH_CEDA_CATALOGUE_API_URL',
  PLANET_CATALOGUE: 'EODH_PLANET_CATALOGUE_API_URL',
  WORKFLOW_RESULT: 'EODH_WORKFLOW_CATALOGUE_API_URL',
};
