export const paths = {
  STAC_ELEMENT_84_CATALOGUE: 'EODH_ELEMENT_84_CATALOGUE_API_URL',
  STAC_CEDA_CATALOGUE: 'EODH_CEDA_CATALOGUE_API_URL',
  PLANET_CATALOGUE: 'EODH_PLANET_CATALOGUE_API_URL',
  WORKFLOW_RESULT: 'EODH_WORKFLOW_CATALOGUE_API_URL',
  STAC_ELEMENT_84_CATALOGUE_INFO: 'EODH_ELEMENT_84_CATALOGUE_INFO_API_URL',
  PLANET_CATALOGUE_INFO: 'EODH_PLANET_CATALOGUE_INFO_API_URL',
};

export const COLLECTION_INFO_ENDPOINTS: Record<string, string> = {
  sentinel1: paths.STAC_ELEMENT_84_CATALOGUE_INFO,
  sentinel2_ard: paths.STAC_ELEMENT_84_CATALOGUE_INFO,
  PSScene: paths.PLANET_CATALOGUE_INFO,
  SkySatCollect: paths.PLANET_CATALOGUE_INFO,
} as const;

export type TCollectionId = keyof typeof COLLECTION_INFO_ENDPOINTS;

export const ALL_COLLECTION_IDS: TCollectionId[] = Object.keys(COLLECTION_INFO_ENDPOINTS) as TCollectionId[];
