on:
  workflow_call:

jobs:
  CheckLint:
    name: 'Run linter and prettier'
    runs-on: ubuntu-20.04
    steps:
      - name: 'Clone repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Install node'
        uses: actions/setup-node@v1
        with:
          node-version: 20.14.0
      - name: 'Install dependencies'
        run: npm ci
      - name: 'Lint check'
        run: npm run lint:check
      - name: 'Prettier check'
        run: npm run format:check
  RunTests:
    name: 'Run tests'
    runs-on: ubuntu-20.04
    steps:
      - name: 'Clone repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Install node'
        uses: actions/setup-node@v1
        with:
          node-version: 20.14.0
      - name: 'Install dependencies'
        run: npm ci
      - name: 'Run unit tests'
        run: npm run test:unit
  BuildAndPublish:
    name: 'Build and publish'
    runs-on: ubuntu-20.04
    steps:
      - name: 'Clone repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Install node'
        uses: actions/setup-node@v1
        with:
          node-version: 20.14.0
      - name: 'Install dependencies'
        run: npm ci
      - name: 'Build'
        run: npm run build
      - name: 'Publish'
        uses: actions/upload-artifact@v4
        with:
          name: image-ukri
          path: dist
