on:
  workflow_call:
    inputs:
      canDeployOnDev:
        required: true
        type: boolean
        default: false
      canDeployOnQA:
        required: true
        type: boolean
        default: false
      canDeployOnStaging:
        required: true
        type: boolean
        default: false
      canDeployOnProduction:
        required: true
        type: boolean
        default: false

jobs:
  deployToDev:
    name: 'Dev'
    uses: ./.github/workflows/deploy.yml
    needs: [prepare, build]
    if: ${{ needs.prepare.outputs.canDeployOnDev == 'true' }}
    with:
      environment: 'dev'
    secrets: inherit
  deployToQa:
    name: 'QA'
    uses: ./.github/workflows/deploy.yml
    needs: [prepare, build]
    if: ${{ needs.prepare.outputs.canDeployOnQA == 'true' }}
    with:
      environment: 'qa'
    secrets: inherit
  deployToStaging:
    name: 'Staging'
    uses: ./.github/workflows/deploy.yml
    needs: [prepare, build, deployToQa]
    if: ${{ needs.prepare.outputs.canDeployOnStaging == 'true' }}
    with:
      environment: 'staging'
    secrets: inherit
  deployToProduction:
    name: 'Production'
    uses: ./.github/workflows/deploy.yml
    needs: [prepare, build, deployToStaging]
    if: ${{ needs.prepare.outputs.canDeployOnProduction == 'true' }}
    with:
      environment: 'prod'
    secrets: inherit
