on:
  workflow_call:
    inputs:
      canDeployOnDev:
        required: true
        type: boolean
        default: false
      canDeployOnQA:
        required: true
        type: boolean
        default: false
      canDeployOnStaging:
        required: true
        type: boolean
        default: false
      canDeployOnProduction:
        required: true
        type: boolean
        default: false

jobs:
  display:
    runs-on: ubuntu-20.04
    steps:
      - run: echo '${{ toJSON(inputs) }}'
  deployToDev:
    name: 'Dev'
    uses: ./.github/workflows/deploy.yml
    if: inputs.canDeployOnDev
    with:
      environment: 'dev'
    secrets: inherit
  deployToQa:
    name: 'QA'
    uses: ./.github/workflows/deploy.yml
    if: inputs.canDeployOnQA
    with:
      environment: 'qa'
    secrets: inherit
  deployToStaging:
    name: 'Staging'
    uses: ./.github/workflows/deploy.yml
    needs: [deployToQa]
    if: inputs.canDeployOnStaging
    with:
      environment: 'staging'
    secrets: inherit
  deployToProduction:
    name: 'Production'
    uses: ./.github/workflows/deploy.yml
    needs: [deployToStaging]
    if: inputs.canDeployOnProduction
    with:
      environment: 'prod'
    secrets: inherit
