on:
  workflow_call:
    inputs:
      canDeployOnDev:
        required: true
        type: boolean
        default: false
      canDeployOnQA:
        required: true
        type: boolean
        default: false
      canDeployOnStaging:
        required: true
        type: boolean
        default: false
      canDeployOnProduction:
        required: true
        type: boolean
        default: false

jobs:
  display:
    runs-on: ubuntu-20.04
    steps:
      - run: echo '${{ toJSON(inputs) }}'
