on:
  workflow_call:
    inputs:
      displayName:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  Deploy:
    name: 'Deploy'
    runs-on: ubuntu-20.04
    steps:
      - name: 'Download build'
        uses: actions/download-artifact@v4
        with:
          name: image-ukri
      - name: 'Deploy to S3'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
          --recursive \
          --acl public-read \
          --region ap-southeast-2 \
          ./build s3://example
