on:
  workflow_call:
    inputs:
      displayName:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  Deploy:
    name: ${{ inputs.displayName }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: ${{ inputs.environment }}
    env:
      testVar: '${{ secrets.awsRoleToAssume }}'
      repoSecret:  '${{ secrets.REPO_SECRET }}'
    steps:
      - name: Print inputs
        run: |
          echo "Display Name: ${{ inputs.displayName }}"
          echo "Environment: ${{ inputs.environment }}"
          echo "MSZ: ${{ secrets.MSZ }}"
          echo "REPO_SECRET ${{ secrets.REPO_SECRET }}"
          echo "MSZ_VAR: ${{ vars.MSZ_VAR }}"
          echo "EXAMPLE_VAR ${{ vars.EXAMPLE_VAR }}"
          echo "AWSROLETOASSUME ${{ secrets.AWSROLETOASSUME }}"
      - name: Run some customized action
        env:
          a: ${{ secrets.AWSBUCKETNAME }}
          b: ${{ secrets.AWSREGION }}
        run: |
          echo $a
          echo $b
      - run: echo '${{ secrets.AWSBUCKETNAME }}'
      - run: echo '${{ secrets.AWSROLETOASSUME }}'
      - run: echo '${{ env.testVar }}'
      - run: echo 'g ${testVar}'
      - name: Echo repository variable EXAMPLE_VAR
        run: echo ${{ vars.EXAMPLE_VAR }}
      - name: Echo env region
        run: echo " ${{ secrets.AWSREGION }} "
      - name: 'Download build'
        uses: actions/download-artifact@v4
        with:
          name: image-ukri
      - name: 'Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWSROLETOASSUME }}
          role-session-name: ${{ secrets.AWSROLESESSIONNAME }}
          aws-region: ${{ secrets.AWSREGION }}
      - name: 'Deploy to S3'
        run: |
          aws s3 cp ./ s3://${{ secrets.AWSBUCKETNAME }}/
