on:
  workflow_call:
    inputs:
      displayName:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  Deploy:
    name: ${{ inputs.displayName }}
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: read
    environment: ${{ inputs.environment }}
    steps:
      - run: echo '${{ secrets.AWS_ROLE_TO_ASSUME }}'
      - run: echo '${{ secrets.AWS_ROLE_SESSION_NAME }}'
      - run: echo '${{ vars.AWS_REGION }}'
      - run: echo '${{ vars.AWS_BUCKET_NAME }}'
      - name: 'Download build'
        uses: actions/download-artifact@v4
        with:
          name: image-ukri
      - name: 'Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: ${{ secrets.AWS_ROLE_SESSION_NAME }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: 'Deploy to S3'
        run: |
          aws s3 cp ./ s3://${{ vars.AWS_BUCKET_NAME }}/
