on:
  workflow_call:
    inputs:
      displayName:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  Deploy:
    name: ${{ inputs.displayName }}
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: read
    #environment: ${{ inputs.environment }}
    environment: dev
    env:
      testVar: '${{ secrets.awsRoleToAssume }}'
    steps:
      - name: Run some customized action
        env:
          a: ${{ secrets.AWSBUCKETNAME }}
          b: ${{ secrets.AWSREGION }}
        run: |
          echo $a
          echo $b
      - run: echo '${{ secrets.AWSBUCKETNAME }}'
      - run: echo '${{ secrets.AWSROLETOASSUME }}'
      - run: echo '${{ env.testVar }}'
      - run: echo 'g ${testVar}'
      - name: Echo repository variable EXAMPLE_VAR
        run: echo ${{ vars.EXAMPLE_VAR }}
      - name: Echo env variable region
        run: echo ${{ secret.AWSREGION }}
      - name: 'Download build'
        uses: actions/download-artifact@v4
        with:
          name: image-ukri
      - name: 'Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.awsRoleToAssume }}
          role-session-name: ${{ secrets.awsRoleSessionName }}
          aws-region: ${{ secrets.awsRegion }}
      - name: 'Deploy to S3'
        run: |
          aws s3 cp ./ s3://${{ secrets.awsBucketName }}/
