on:
  pull_request:
    branches:
      - 'develop'
      - 'main'
      - 'release/**'

env:
  isDevelop: ${{ startsWith(github.baseRef, 'refs/heads/develop') }}
  isRelease: ${{ startsWith(github.baseRef, 'refs/heads/release/') }}
  isHotfix: ${{ startsWith(github.baseRef, 'refs/heads/hotfix/') }}
  isMain: ${{ startsWith(github.baseRef, 'refs/heads/main') }}
  isCiCdTest: ${{ startsWith(github.baseRef, 'refs/heads/feature/ci-cd') }}

jobs:
  build:
    uses: ./.github/workflows/build.yml
  deployToDev:
    uses: ./.github/workflows/deploy.yml
    needs: [build]
    if: ${{ env.isDevelop || env.isHotfix || env.isCiCdTest }}
    with:
      displayName: 'Deploy to Dev'
      environment: 'dev'
  deployToQa:
    uses: ./.github/workflows/deploy.yml
    needs: [build]
    if: ${{ env.isDevelop || env.isHotfix || env.isRelease }}
    with:
      displayName: 'Deploy to Dev'
      environment: 'qa'
  deployToStaging:
    uses: ./.github/workflows/deploy.yml
    needs: [build, deployToQa]
    if: ${{ env.isHotfix || env.isRelease }}
    with:
      displayName: 'Deploy to Staging'
      environment: 'staging'
  deployToProduction:
    uses: ./.github/workflows/deploy.yml
    needs: [build, deployToStaging]
    if: ${{ env.isHotfix || env.isRelease || env.isMaster }}
    with:
      displayName: 'Deploy to Production'
      environment: 'prod'
