on:
  pull_request:
    branches:
      - 'develop'
      - 'main'
      - 'release/**'

env:
  isDevelop: ${{ startsWith(github.base_ref, 'refs/heads/develop') }}
  isRelease: ${{ startsWith(github.base_ref, 'refs/heads/release/') }}
  isHotfix: ${{ startsWith(github.base_ref, 'refs/heads/hotfix/') }}
  isMain: ${{ startsWith(github.base_ref, 'refs/heads/main') }}
  isCiCdTest: ${{ startsWith(github.base_ref, 'refs/heads/feature/ci-cd') }}

permissions:
  id-token: write
  contents: read

jobs:
  prepare:
    name: 'Setup variables'
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(github) }}'
      - run: echo "Setup variables"
    outputs:
      canDeployOnDev: ${{ env.isDevelop || env.isHotfix || env.isCiCdTest }}
      canDeployOnQA: ${{ env.isDevelop || env.isHotfix || env.isRelease }}
      canDeployOnStaging: ${{ env.isHotfix || env.isRelease }}
      canDeployOnProduction: ${{ env.isHotfix || env.isRelease || env.isMaster }}
  build:
    uses: ./.github/workflows/build.yml
  deployToDev:
    uses: ./.github/workflows/deploy.yml
    needs: [prepare, build]
    if: needs.prepare.outputs.canDeployOnDev
    with:
      displayName: 'Deploy to Dev'
      environment: 'dev'
  deployToQa:
    uses: ./.github/workflows/deploy.yml
    needs: [prepare, build]
    if: needs.prepare.outputs.canDeployOnQA
    with:
      displayName: 'Deploy to Dev'
      environment: 'qa'
  deployToStaging:
    uses: ./.github/workflows/deploy.yml
    needs: [prepare, build, deployToQa]
    if: needs.prepare.outputs.canDeployOnStaging
    with:
      displayName: 'Deploy to Staging'
      environment: 'staging'
  deployToProduction:
    uses: ./.github/workflows/deploy.yml
    needs: [prepare, build, deployToStaging]
    if: needs.prepare.outputs.canDeployOnProduction
    with:
      displayName: 'Deploy to Production'
      environment: 'prod'
