on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'release/**'
      - 'feature/**'

env:
  isDevelop: ${{ startsWith(github.ref, 'refs/heads/develop') }}
  isRelease: ${{ startsWith(github.ref, 'refs/heads/release/') }}
  isHotfix: ${{ startsWith(github.ref, 'refs/heads/hotfix/') }}
  isMain: ${{ startsWith(github.ref, 'refs/heads/main') }}
  isCiCdTest: ${{ startsWith(github.ref, 'refs/heads/feature/ci-cd') }}

permissions:
  id-token: write
  contents: read

jobs:
  prepare:
    name: 'Setup variables'
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Setup variables"
    outputs:
      canDeployOnDev: ${{ fromJSON(env.isDevelop) || fromJSON(env.isHotfix) || fromJSON(env.isCiCdTest) }}
      canDeployOnQA: ${{ fromJSON(env.isDevelop) || fromJSON(env.isHotfix) || fromJSON(env.isRelease) || fromJSON(env.isMain) }}
      canDeployOnStaging: ${{ fromJSON(env.isHotfix) || fromJSON(env.isRelease) || fromJSON(env.isMain) }}
      canDeployOnProduction: ${{ fromJSON(env.isHotfix) || fromJSON(env.isRelease) || fromJSON(env.isMain) }}
  build:
    name: 'Build'
    uses: ./.github/workflows/build.yml
  deployToDev:
    name: 'Deploy'
    uses: ./.github/workflows/deploy.yml
    needs: [prepare, build]
    if: ${{ needs.prepare.outputs.canDeployOnDev == 'true' }}
    with:
      environment: 'dev'
      displayName: 'Dev'
    secrets: inherit
  deployToQa:
    name: 'Deploy'
    uses: ./.github/workflows/deploy.yml
    needs: [prepare, build]
    if: ${{ needs.prepare.outputs.canDeployOnQA == 'true' }}
    with:
      environment: 'qa'
      displayName: 'QA'
    secrets: inherit
  deployToStaging:
    name: 'Deploy'
    uses: ./.github/workflows/deploy.yml
    needs: [prepare, build, deployToQa]
    if: ${{ needs.prepare.outputs.canDeployOnStaging == 'true' }}
    with:
      environment: 'staging'
      displayName: 'Staging'
    secrets: inherit
#  deployToProduction:
#    name: 'Deploy'
#    uses: ./.github/workflows/deploy.yml
#    needs: [prepare, build, deployToStaging]
#    if: ${{ needs.prepare.outputs.canDeployOnProduction == 'true' }}
#    with:
#      environment: 'prod'
#      displayName: 'Production'
#    secrets: inherit
