on:
  pull_request:
    branches:
      - 'develop'
      - 'main'
      - 'release/**'

env:
  isDevelop: ${{ startsWith(github.base_ref, 'develop') }}
  isRelease: ${{ startsWith(github.base_ref, 'release/') }}
  isHotfix: ${{ startsWith(github.base_ref, 'hotfix/') }}
  isMain: ${{ startsWith(github.base_ref, 'main') }}
  isCiCdTest: ${{ startsWith(github.base_ref, 'feature/ci-cd') }}

permissions:
  id-token: write
  contents: read

jobs:
  prepare:
    name: 'Setup variables'
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(github) }}'
      - run: echo '${{ toJSON(env) }}'
      - run: echo 'canDeployOnDev ${{ env.isDevelop || env.isHotfix || env.isCiCdTest }}'
      - run: echo 'canDeployOnQA ${{ env.isDevelop || env.isHotfix || env.isRelease }}'
      - run: echo 'canDeployOnStaging ${{ env.isHotfix || env.isRelease }}'
      - run: echo 'canDeployOnProduction ${{ env.isHotfix || env.isRelease || env.isMaster }}'
      - run: echo "Setup variables"
    outputs:
      canDeployOnDev: ${{ env.isDevelop || env.isHotfix || env.isCiCdTest }}
      canDeployOnQA: ${{ env.isDevelop || env.isHotfix || env.isRelease }}
      canDeployOnStaging: ${{ env.isHotfix || env.isRelease }}
      canDeployOnProduction: ${{ env.isHotfix || env.isRelease || env.isMaster }}
  prepare2:
    name: 'Log variables'
    needs: [prepare]
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(needs.prepare.outputs) }}'
      - run: echo "Log variables"
  build:
    name: 'Build'
    uses: ./.github/workflows/build.yml
  deployToDev:
    name: 'Deploy'
    uses: ./.github/workflows/deploy.yml
    needs: [prepare, build]
    if: ${{ needs.prepare.outputs.canDeployOnDev == 'true' }}
    with:
      environment: 'dev'
      displayName: 'Dev'
  deployToQa:
    name: 'Deploy'
    uses: ./.github/workflows/deploy.yml
    needs: [prepare, build]
    if: ${{ needs.prepare.outputs.canDeployOnQA == 'true' }}
    with:
      environment: 'qa'
      displayName: 'QA'
  deployToStaging:
    name: 'Deploy'
    uses: ./.github/workflows/deploy.yml
    needs: [prepare, build, deployToQa]
    if: ${{ needs.prepare.outputs.canDeployOnStaging == 'true' }}
    with:
      environment: 'staging'
      displayName: 'Staging'
  deployToProduction:
    name: 'Deploy'
    uses: ./.github/workflows/deploy.yml
    needs: [prepare, build, deployToStaging]
    if: ${{ needs.prepare.outputs.canDeployOnProduction == 'true' }}
    with:
      environment: 'prod'
      displayName: 'Production'
