on:
  pull_request:
    branches:
      - 'develop'
      - 'main'
      - 'release/**'

env:
  isDevelop: ${{ startsWith(github.head_ref, 'develop') }}
  isRelease: ${{ startsWith(github.head_ref, 'release/') }}
  isHotfix: ${{ startsWith(github.head_ref, 'hotfix/') }}
  isMain: ${{ startsWith(github.head_ref, 'main') }}
  isCiCdTest: ${{ startsWith(github.head_ref, 'feature/ci-cd') }}

permissions:
  id-token: write
  contents: read

jobs:
  prepare:
    name: 'Setup variables'
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Setup variables"
    outputs:
      canDeployOnDev: ${{ env.isDevelop || env.isHotfix || env.isCiCdTest }}
      canDeployOnQA: ${{ env.isDevelop || env.isHotfix || env.isRelease }}
      canDeployOnStaging: ${{ env.isHotfix || env.isRelease }}
      canDeployOnProduction: ${{ env.isHotfix || env.isRelease || env.isMaster }}
  build:
    name: 'Build'
    uses: ./.github/workflows/build.yml
  deployToDev:
    name: 'Deploy'
    uses: ./.github/workflows/deploy.yml
    needs: [prepare, build]
    if: ${{ needs.prepare.outputs.canDeployOnDev == 'true' }}
    with:
      environment: 'dev'
      displayName: 'Dev'
    secrets: inherit
  deployToQa:
    name: 'Deploy'
    uses: ./.github/workflows/deploy.yml
    needs: [prepare, build]
    if: ${{ needs.prepare.outputs.canDeployOnQA == 'true' }}
    with:
      environment: 'qa'
      displayName: 'QA'
    secrets: inherit
  deployToStaging:
    name: 'Deploy'
    uses: ./.github/workflows/deploy.yml
    needs: [prepare, build, deployToQa]
    if: ${{ needs.prepare.outputs.canDeployOnStaging == 'true' }}
    with:
      environment: 'staging'
      displayName: 'Staging'
    secrets: inherit
  deployToProduction:
    name: 'Deploy'
    uses: ./.github/workflows/deploy.yml
    needs: [prepare, build, deployToStaging]
    if: ${{ needs.prepare.outputs.canDeployOnProduction == 'true' }}
    with:
      environment: 'prod'
      displayName: 'Production'
    secrets: inherit
