on:
  pull_request:
    branches:
      - 'develop'
      - 'main'

jobs:
  build:
    name: 'Build'
    uses: ./.github/workflows/build.yml
  buildStorybook:
    name: 'Build Storybook'
    uses: ./.github/workflows/storybook-build.yml
  deploy:
    name: 'Deploy'
    uses: ./.github/workflows/deploy.yml
    needs: [build]
    with:
      canDeployOnDev: ${{ fromJSON('true') }}
      canDeployOnQA: ${{ fromJSON(needs.prepare.outputs.canDeployOnQA) }}
      canDeployOnStaging: ${{ fromJSON(needs.prepare.outputs.canDeployOnStaging) }}
      canDeployOnProduction: ${{ fromJSON(needs.prepare.outputs.canDeployOnProduction) }}
    secrets: inherit
