on:
  pull_request:
    branches:
      - 'develop'
      - 'main'

jobs:
  build:
    name: 'Build'
    uses: ./.github/workflows/build.yml
  buildStorybook:
    name: 'Build Storybook'
    uses: ./.github/workflows/storybook-build.yml
