on:
  pull_request:
    branches:
      - 'develop'
      - 'main'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: 'Build'
    uses: ./.github/workflows/build.yml
  buildStorybook:
    name: 'Build Storybook'
    uses: ./.github/workflows/storybook-build.yml
  deploy:
    name: 'Deploy'
    uses: ./.github/workflows/deploy.yml
    needs: [build]
    with:
      canDeployOnDev: true
      canDeployOnQA: true
      canDeployOnStaging: false
      canDeployOnProduction: false
    secrets: inherit
  deployStorybook:
    name: 'Deploy Storybook'
    uses: ./.github/workflows/storybook-deploy.yml
    needs: [buildStorybook]
    with:
      canDeploy: true
    secrets: inherit
