on:
  push:
    branches:
      - 'main'
      - 'develop'

env:
  isDevelop: ${{ startsWith(github.ref, 'refs/heads/develop') }}
  isRelease: ${{ startsWith(github.ref, 'refs/heads/release/') }}
  isHotfix: ${{ startsWith(github.ref, 'refs/heads/hotfix/') }}
  isMain: ${{ startsWith(github.ref, 'refs/heads/main') }}
  isCiCdTest: ${{ startsWith(github.ref, 'refs/heads/feature/ci-cd') }}

permissions:
  id-token: write
  contents: read

jobs:
  prepare:
    name: 'Setup variables'
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Setup variables"
    outputs:
      canDeployOnDev: ${{ fromJSON(env.isDevelop) || fromJSON(env.isHotfix) || fromJSON(env.isCiCdTest) }}
      canDeployOnQA: ${{ fromJSON(env.isDevelop) || fromJSON(env.isHotfix) || fromJSON(env.isRelease) || fromJSON(env.isMain) }}
      canDeployOnStaging: ${{ fromJSON(env.isHotfix) || fromJSON(env.isRelease) || fromJSON(env.isMain) }}
      canDeployOnProduction: ${{ fromJSON(false) }}
  build:
    name: 'Build'
    uses: ./.github/workflows/build.yml
  deploy:
    name: 'Deploy'
    uses: ./.github/workflows/deploy-to-environments.yml
    needs: [prepare, build]
    with:
      canDeployOnDev: ${{ needs.prepare.outputs.canDeployOnDev }}
      canDeployOnQA: ${{ needs.prepare.outputs.canDeployOnQA }}
      canDeployOnStaging: ${{ needs.prepare.outputs.canDeployOnStaging }}
      canDeployOnProduction: ${{ needs.prepare.outputs.canDeployOnProduction }}
    secrets: inherit
