on:
  push:
    branches:
      - 'main'
      - 'develop'

env:
  isDevelop: ${{ startsWith(github.ref, 'refs/heads/develop') }}
  isRelease: ${{ startsWith(github.ref, 'refs/heads/release/') }}
  isHotfix: ${{ startsWith(github.ref, 'refs/heads/hotfix/') }}
  isMain: ${{ startsWith(github.ref, 'refs/heads/main') }}
  isCiCdTest: ${{ startsWith(github.ref, 'refs/heads/feature/ci-cd') }}

permissions:
  id-token: write
  contents: read

jobs:
  prepare:
    name: 'Setup variables'
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Setup variables"
    outputs:
      canDeployOnDev: ${{ env.isDevelop || env.isHotfix || env.isCiCdTest }}
      canDeployOnQA: ${{ env.isDevelop || env.isHotfix || env.isRelease || env.isMain }}
      canDeployOnStaging: ${{ env.isHotfix || env.isRelease || env.isMain }}
      canDeployOnProduction: ${{ env.isHotfix || env.isRelease || env.isMain }}
  build:
    name: 'Build'
    uses: ./.github/workflows/build.yml
  deploy:
    name: 'Deploy'
    uses: ./.github/workflows/deploy-to-environments.yml
    needs: [prepare, build]
    with:
      canDeployOnDev: ${{ fromJSON(needs.prepare.outputs.canDeployOnDev) }}
      canDeployOnQA: ${{ fromJSON(needs.prepare.outputs.canDeployOnQA) }}
      canDeployOnStaging: ${{ fromJSON(needs.prepare.outputs.canDeployOnStaging) }}
      canDeployOnProduction: ${{ fromJSON(needs.prepare.outputs.canDeployOnProduction) }}
    secrets: inherit
