on:
  workflow_call:

jobs:
  BuildAndPublish:
    name: 'Build and publish'
    runs-on: ubuntu-24.04
    steps:
      - name: 'Clone repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Install node'
        uses: actions/setup-node@v4
        with:
          node-version: 20.14.0
      - name: 'Install dependencies'
        run: npm ci --include=optional
      - name: 'Build'
        run: npm run build:storybook
        env:
          VITE_BASE_URL: ${{ vars.APP_BASE_URL }}
          VITE_EODH_COLLECTION_INFO_API_URL: ${{ vars.APP_EODH_COLLECTION_INFO_API_URL }}
          VITE_EODH_ELEMENT_84_CATALOGUE_API_URL: ${{ vars.APP_EODH_ELEMENT_84_CATALOGUE_API_URL }}
          VITE_EODH_CEDA_CATALOGUE_API_URL: ${{ vars.APP_EODH_CEDA_CATALOGUE_API_URL }}
          VITE_EODH_PLANET_CATALOGUE_API_URL: ${{ vars.APP_EODH_PLANET_CATALOGUE_API_URL }}
          VITE_EODH_WORKFLOW_CATALOGUE_API_URL: ${{ vars.APP_EODH_WORKFLOW_CATALOGUE_API_URL }}
          VITE_EODH_PRO_API_URL: ${{ vars.APP_EODH_PRO_API_URL }}
          VITE_EODH_PAGE_URL: ${{ vars.APP_EODH_PAGE_URL }}
          VITE_TRANSLATION_LANGUAGE: ${{ vars.APP_TRANSLATION_LANGUAGE }}
          VITE_TRANSLATION_FALLBACK_LANGUAGE: ${{ vars.APP_TRANSLATION_FALLBACK_LANGUAGE }}
          VITE_AUTHORIZATION_URL: ${{ vars.APP_AUTHORIZATION_URL }}
          VITE_AUTHORIZATION_REALM: ${{ vars.APP_AUTHORIZATION_REALM }}
          VITE_AUTHORIZATION_CLIENT_ID: ${{ vars.APP_AUTHORIZATION_CLIENT_ID }}
          VITE_AUTHORIZATION_SCOPES: ${{ vars.APP_AUTHORIZATION_SCOPES }}
          VITE_BUILD_VERSION_NUMBER: ${{ github.run_id }}
      - name: 'Publish'
        uses: actions/upload-artifact@v4
        with:
          name: image-ukri-storybook
          path: dist/storybook/storybook-host
