on:
  workflow_call:
    inputs:
      canDeploy:
        required: true
        type: boolean
        default: false

jobs:
  deployToDev:
    name: 'Dev'
    if: inputs.canDeploy
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: read
    environment: 'storybook'
    steps:
      - name: 'Download build'
        uses: actions/download-artifact@v4
        with:
          name: image-ukri-storybook
      - name: 'Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: ${{ vars.AWS_ROLE_SESSION_NAME }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: 'Deploy to S3'
        run: aws s3 cp ./ s3://${{ vars.AWS_BUCKET_NAME }}/ --recursive
      - name: 'Invalidate CloudFront'
        run: aws cloudfront create-invalidation --distribution-id ${{ vars.DISTRIB_ID }} --paths "/*"
